### ISSUE TITLE
Automate build and deploy of Workshop website

### ISSUE THREAD

**Issue by practicalli-johnny** [ClojureBridgeLondon/workshop-content-gitbook#43]
UPDATE: GitBook.io open source tool has not been maintained for many years, so this content will be migrated to MkDocs.

The plan is to create a Practicalli Learn Clojure book with the content written by John Stevenson and deprecate the ClojureBridge London workshop site.

#### Original Plan
Add GitHub actions to automate the building, verification and deployment of the workshop content on GitHub pages

#### Tasks

* [ ] Add GitHub actions to build and deploy the workshop content from this repository to GitHub pages (see practicalli/clojure for an example)
* [ ] Configure GitHub pages to server from `gh-pages` branch
* [ ] Configure domain (if we have one) and set HTTPS connection
* [ ] Test GitHub pages are building and being served correctly 
* [ ] Remove the clojurebridgelondon/workshop repository (currently holds the generated output)
* [ ] Rename clojurebridgelondon/workshop-content-gitbook to clojurebrigelondon/workshop
* [ ] Test that https://clojurebridgelondon.github.io/workshop is working correctly
